# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'OoyalaSDKPodSampleApp' do

pod 'OoyalaSDK', '~> 3.5.0'

end

target 'OoyalaSDKPodSampleAppTests' do

end

